/**
 ******************************************************************************
 * DO NOT MANUALLY EDIT THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED.
 ******************************************************************************
 */

export interface LiveExample {
  /** Title of the example. */
  title: string;
  /** Name of the example component. */
  componentName: string;
  /** Selector to match the component of this example. */
  selector: string;
  /** Name of the primary file of this example. */
  primaryFile: string;
  /** List of files which are part of the example. */
  files: string[];
  /** Path to the directory containing the example. */
  packagePath: string;
  /** List of additional components which are part of the example. */
  additionalComponents: string[];
  /** NgModule that declares this example. */
  module: NgModuleInfo;
}

export interface NgModuleInfo {
  /** Name of the NgModule. */
  name: string;
  /**
   * Import specifier that resolves to this module. The specifier is not scoped to
   * `@angular/components-examples` because it's up to the consumer how the module is
   * imported. For example, in the docs app, modules are lazily imported from `fesm2015/`.
   */
  importSpecifier: string;
}

export const EXAMPLE_COMPONENTS: {[id: string]: LiveExample} = {
  "solution-one": {
    "packagePath": "lib/route-reuse-strategy/parent-child-design/solution-one",
    "title": "Solution One",
    "componentName": "SolutionOneComponent",
    "files": [
      "solution-one.component.ts",
      "./solution-one.component.html",
      "./solution-one.component.css"
    ],
    "selector": "lib-solution-one",
    "additionalComponents": [],
    "primaryFile": "solution-one.component.ts",
    "module": {
      "name": "ParentChildDesignModule",
      "importSpecifier": "lib/route-reuse-strategy/parent-child-design"
    }
  },
  "solution-three": {
    "packagePath": "lib/route-reuse-strategy/parent-child-design/solution-three",
    "title": "Solution Three",
    "componentName": "SolutionThreeComponent",
    "files": [
      "solution-three.component.ts",
      "./solution-three.component.html",
      "./solution-three.component.css"
    ],
    "selector": "lib-solution-three",
    "additionalComponents": [],
    "primaryFile": "solution-three.component.ts",
    "module": {
      "name": "ParentChildDesignModule",
      "importSpecifier": "lib/route-reuse-strategy/parent-child-design"
    }
  },
  "solution-two": {
    "packagePath": "lib/route-reuse-strategy/parent-child-design/solution-two",
    "title": "Solution Two",
    "componentName": "SolutionTwoComponent",
    "files": [
      "solution-two.component.ts",
      "./solution-two.component.html",
      "./solution-two.component.css"
    ],
    "selector": "lib-solution-two",
    "additionalComponents": [],
    "primaryFile": "solution-two.component.ts",
    "module": {
      "name": "ParentChildDesignModule",
      "importSpecifier": "lib/route-reuse-strategy/parent-child-design"
    }
  }
};